### ISSUE TITLE
Efraim has lost lesser berserk attack?

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#236]
At the end of LotI 1 
Efraim advancement shows he should have lesser_berserk_5 , but the right side panel show nothing (and attack has deseappered)

Is it a feature due to the end of part 1 ?  
If so i have missed a message

![efraim_no_lesser_berserk](https://user-images.githubusercontent.com/31039036/51436484-2f89bb00-1c8e-11e9-8852-1729d37d412d.png)

[LotI1-Magic Power Amplificator 2 Tour 3_Efraim_no_lesser_berserk.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/2776354/LotI1-Magic.Power.Amplificator.2.Tour.3_Efraim_no_lesser_berserk.gz)

**Comment by Dugy** [comment]
It has been fixed at some point, because when I try it now, he gains it back when I make an operation that causes his attacks to be recalculated.

**Comment by alain-bkr** [comment]
How to make his attacks to be recalculated? For me the bug is still present.

I retried with 1.14.4 and LotI from git :
commit 76c3ae96b154e136c4bcccc4b5ee75c5f04cbc48 (HEAD -> master, origin/master, origin/HEAD)
Date:   Thu Jan 17 23:53:09 2019 +0300

**Comment by Dugy** [comment]
Unequip an item or equip a new item, have the unit advance, change the last advancement...

Your version is out of date, that could be the cause. A lot of changes are being done in the repository.
